services:
  - type: web
    name: salas-conectadas-cepi
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: salas-conectadas-db
          property: connectionString
      - key: PORT
        value: 5000

databases:
  - name: salas-conectadas-db
    databaseName: salas_conectadas_cepi
    plan: free